# @package _global_
engine_name: extract_features
config:
  VERBOSE: True
  SEED_VALUE: 0
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DATA_SOURCES: [disk_folder]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      LABEL_TYPE: sample_index
      BATCHSIZE_PER_REPLICA: 64
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: False
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      ENABLE_QUEUE_DATASET: False
      # COLLATE_FUNCTION: simclr_collator
      # DROP_LAST: True
    TEST:
      DATA_SOURCES: [disk_folder]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 64
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: False
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      ENABLE_QUEUE_DATASET: False
      # COLLATE_FUNCTION: simclr_collator
      # DROP_LAST: True
  MODEL:
    WEIGHTS_INIT:
      PARAMS_FILE: "<path to .torch file>"
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_AND_HEAD: True
      EVAL_TRUNK_AND_HEAD: True
      # SHOULD_FLATTEN_FEATS: True
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["conv1", ["AvgPool2d", [[10, 10], 10, 4]]],
        ["res2", ["AvgPool2d", [[16, 16], 8, 0]]],
        ["res3", ["AvgPool2d", [[13, 13], 5, 0]]],
        ["res4", ["AvgPool2d", [[8, 8], 3, 0]]],
        ["res5", ["AvgPool2d", [[6, 6], 1, 0]]],
      ]
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
    HEAD:
      # Set num classes
      PARAMS: [
        ["eval_mlp", {"in_channels": 64, "dims": [9216, 10]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 10]}],
        ["eval_mlp", {"in_channels": 512, "dims": [8192, 10]}],
        ["eval_mlp", {"in_channels": 1024, "dims": [9216, 10]}],
        ["eval_mlp", {"in_channels": 2048, "dims": [8192, 10]}],
      ]
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1
    RUN_ID: auto
    INIT_METHOD: tcp
    NCCL_DEBUG: True
  MACHINE:
    DEVICE: gpu
  EXTRACT_FEATURES:
    OUTPUT_DIR: "<features output path>"
    CHUNK_THRESHOLD: 0
    # MAP_FEATURES_TO_IMG_NAME: True
